### ISSUE TITLE
Why was fitted_lavaan.R dropped?

### ISSUE THREAD

**Issue by dmcglinn** [simsem/semTools#110]
I am interested in making predictions with an sem model. I found a reference here: 

https://groups.google.com/g/lavaan/c/PmvWW0RgyvA

to the script `fitted_lavann.R`. But I can see now that this script is no long part of the R package. 

Was this code found to be buggy or just outside of the scope of the project? It seems like a useful approach. I see something similar but not as well documented is implemented here: 

https://github.com/jebyrnes/spatial_correction_lavaan/blob/master/predict_lavaan.R 

Thank you for your great work!

**Comment by TDJorgensen** [comment]
This was never part of `semTools`.  It was a script provided by a user for consideration (#25).  I made some feedback about incorporating it, and somebody else took up the project briefly, but it has been stuck in limbo for a long time.  You don't need it to be in `semTools` in order to `source()` the file and use it.  But if someone has the time to add the checks and write a test script investigating a set of situations, I would be happy to include it in `semTools`.
