### ISSUE TITLE
Error in scalar invariance using  measEq.syntax

### ISSUE THREAD

**Issue by hynekcigler** [simsem/semTools#60]
Hi. My student got unpleasant error using measEq.syntax function at scalar level. The problem was probably the bifactor measurement model (and possibly ordinal items?). Configural model was specified as

model <- "
DEP =~ PHQ1 + PHQ2 + PHQ3 + PHQ4 + PHQ5 + PHQ6 + PHQ7  + PHQ8 + PHQ9
S1 =~ PHQ7 + equal('S1=~PHQ7')*PHQ8
S2 =~ PHQ3 + PHQ4 + PHQ5
S1 ~~ S2 ## don't ask :)
"

and the function syntax as

scalar_model_OBCvsT_mod <- measEq.syntax(modelINVALL, LONG_OBCvsT, group = "skupina", 
                                    std.lv = T, orthogonal = T, 
                                    ordered=names(LONG_OBCvsT),
                                    parameterization = "theta", return.fit = F, 
                                    estimator = "WLSMV",
                                    missing = "pairwise",
                                    group.equal = c("thresholds", "loadings", "intercepts"))

Unfortunately, the latent means were not released for the specific factors, returning

LATENT MEANS/INTERCEPTS:
DEP ~ c(alpha.1.g1, alpha.1.g2)*1 + c(0, NA)*1
S1 ~ c(alpha.2.g1, alpha.2.g2)*1 + c(0, 0)*1
S2 ~ c(alpha.3.g1, alpha.3.g2)*1 + c(0, 0)*1

We released means in alpha matrix manually, but it took a lot of time to identify why the model was not invariant. But anyway, thank you for a great function, especially methods for identifying ordinal models works excellently!

**Comment by TDJorgensen** [comment]
> The problem was probably the bifactor measurement model

Indeed, this comment is in my source code:
```
##TODO: Notes for help page:
##  - without a unique indicator per construct, constraining intercepts does
##    not free latent means, even if they can be identified.
##  - Must free manually if (ID.fac == "uv") OR set ID.fac == "ul" (not "fx")
```
Not that I expect users to read my source code :-)  But I was aware of this issue, and there is not an obvious solution.  From a practical standpoint, there is no way to tell your model syntax specifies a bifactor model, as opposed to any other model that has cross-loadings (including the extreme case of an exploratory factor analysis model with all possible cross-loadings).  Note that this issue does not come up for factor loadings/variances because (co)variances can be partitioned into components, whereas an observed variable only has 1 mean (and/or set of thresholds, if `ordered`) that cannot be partitioned into "location due to different factors" (well, it could, but only in a completely arbitrary way; intercepts would all be 3 points lower if we arbitrarily fixed residuals' means to be 3 instead of 0).

Unfortunately, I cannot think of a straight-forward algorithm to identify situations when a particular factor has a sufficient number of unique indicators whose intercepts are sufficiently constrained to identify the factor's mean, unless of course for the obvious case when the factor's first indicator's intercept is fixed to zero (and each factor has a different "first" indicator).  

In your example, all latent means would be identified in group 2, but only the latent mean of DEP (in group 2) is recognized as identified because it has unique indicators that do not have cross-loadings on a method factor.  If you set `ID.fac = "ul"` (and omit the completely unnecessary `std.lv = TRUE` that conflicts with the `ID.fac` argument), then your latent means will all be free by default, which is only a problem if you find evidence against the null hypothesis of full invariance of loadings & intercepts (because the marker variable could have DIF).  But using `ID.fac = "uv"` (which I do recommend) unfortunately requires you to manually free the means in the syntax generated by `measEq.syntax()`, and it will remain that way unless a sufficiently general algorithm  becomes apparent.

But I did add a warning if any cross-loadings are detected (bifactor models or otherwise) and intercepts are constrained to equality when `ID.fac="std.lv"`, but means are not constrained.  In that case, the warning tells the user to check the syntax returned by the function to see whether means need to be manually freed.  

Please let me know if that correctly identifies your case, and if you find the warning message sufficiently informative.  Thanks.

**Comment by hynekcigler** [comment]
Oh, thank you for very detailed response! You are right, I did not check you syntax of course :) , but I do now understand why the means are not freed (I did no imagine the situation where the latent means were not identified without any specific indicator). 
We already manually released means in the syntax produced by measEq.syntax yesterday (however it did not help as the WLSMV estimator failed to find solution; the data came from pregnant women and mothers with 3 months-old children, so the item asking about sleeping had so huge DIF that it couldn't work). But thank you a lot for examples using the ID.fac; I skipped this argument and it is great. 

I looked in the source code and the warning is nice and clear. However, I have an idea: would it be possible to add a parameter, which would overwrite the other arguments and which contains a vector with factor names to be released in all the groups (except the first one)? It would help with not only the bifactor models but probably also in other cases. 

Thank you!

**Comment by TDJorgensen** [comment]
> would it be possible to add a parameter, which would overwrite the other arguments and which contains a vector with factor names to be released in all the groups (except the first one)? It would help with not only the bifactor models but probably also in other cases.

I finally worked out a general enough idea. I added an argument to the `update()` method to `change.syntax=` by passing lavaan syntax to replace the specification of any parameter(s).  This should work fine your needs, as well as other cases.  For example, `group.partial=` frees a parameter across all groups (likewise for `long.partial=` across all repeated measures). When it is of interest to free a parameter only in one group (leaving the equality constraints in place among remaining groups), `update()` provides the required flexibility so that users don't have to copy/paste the script into an R script to edit manually.

```
devtools::install_github("simsem/semTools/semTools")
```

Here's an arbitrary example:

```
library(semTools) # 0.5-2.914
HS.model <- ' visual =~ x1 + x2 + x3 '
fit <- cfa(HS.model, data = HolzingerSwineford1939, group = "school", std.lv = TRUE)
stx <- measEq.syntax(fit, group.equal = "loadings")
cat(as.character(stx))
## fix variance to 1 in second group instead of first, and customize labels
switched <- update(stx, change.syntax = "visual ~~ c(NA, 1)*visual + c(foo, bar)*visual")
cat(as.character(switched))
```

The customization will continue to be respected if you further `update()` the `switched` object, because any previously accumulated changes are stored in the new `switched@updates` slot.

```
cat(as.character(update(switched, change.syntax = "visual =~ L1*x1 + L2*x2 + L3*x3")))
```

**Comment by hynekcigler** [comment]
The `update` function is amazing and it really helps. Thank you very much! :-)
