### ISSUE TITLE
Probing interactions estimated with MLR

### ISSUE THREAD

**Issue by eavaladez** [simsem/semTools#87]
Hello semToolers,

I have a model with 2- and 3-way interactions that was estimated using MLR. All variables are continuous. I would like to probe the interactions, but it seems the "probe2Way..." and "probe3Way..." functions do not work with MLR estimation. I get the following error:
    
    This function does not work when 'mlr', 'mlm', or 'mlf' is used as the estimator because the covariance matrix of the parameter estimates cannot be computed.

I seem to recall that this was possible in an earlier version of semTools. Are there any plans to handle MLR in the future? Would the results be wrong if I were to bypass this check?

Thanks very much,
Emilio

**Comment by TDJorgensen** [comment]
Sunthud put that check in there, so it has been there for years.  But I don't know if it was ever necessary.  The comment in the source code made it sound as though the full ACOV was not robust when robust *SE*s were requested, but it is.  I removed the check of the estimator, since I do not think it is relevant (except that DWLS, MML, or PML are all for categorical data, in which case product indicators do not make sense anyway).  You can install development version 0.5-4.910 to use this (also see #88)

**Comment by eavaladez** [comment]
Very good to know! Thanks!
